### ISSUE TITLE
Bienvenidos a issues, poned aquí vuestros problemas.

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#1]

**Comment by ecoronado96** [comment]
Comento un **error que puede darse al ejecutar el juego**. Es un error **referente a Windows y sus notificaciones**. En mi caso aparecía una notificación indicándome que la resolución recomendada para el equipo es 1080p no 720p; las notificaciones de Windows suelen aparecer por encima de los programas que utilizamos con frecuencia en la esquina inferior izquierda, nuestro juego no es distinto, pero no permite que se visualice la notificación; en el estado combate el menú de selección derecha ocupa ese área en concreto, por lo tanto en el caso de que veáis que no responde o que se tabula el juego al clickar sobre uno de los elementos, muy probablemente tengáis alguna notificación de Windows; con **cerrar las notificaciones debería de ser suficiente para que funcionase correctamente.**
