### ISSUE TITLE
Paquete de texturas

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#10]
El juego se ambienta en un bosque (p.e Ronda o Cantabria) en época veraniega.
Se requiere un total de 2 o 3 paquetes de texturas, para que podamos elegir los que mas nos gusten.

**Comment by MarinaFer** [comment]
![Nivel 1](https://user-images.githubusercontent.com/46962469/56770627-c47fe100-67b4-11e9-995e-5a32893ffb4c.png)

El resultado con los paquetes de textura elegidos sería este primer nivel con la casa de la abuela de Ruby y el bosque de fondo.

Si @Pepooliet @ecoronado96 @Javier-DlaP @KinGJV están de acuerdo en dejarlo como está actualmente se daría por completado este nivel.
