### ISSUE TITLE
Sistema de bocadillos

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#13]
Vamos a empezar con el sistema de bocadillos. Para ello haremos que al clickar una celda se despliegue un bocadillo. Este además tiene que cumplir con lo siguiente.

- Tiene que mostrar un texto dentro
- Al pulsar una tecla pasa de una diapositiva a la siguiente.
- (OPCIONAL) Se debe detener el juego

**Comment by Javier-DlaP** [comment]
Acabado.
Al final conseguí que los bocadillos se ajustasen a la resolución de pantalla que uno tengo, el único problema sería que a resoluciones muy grandes como 4k las letras se verían algo pequeñas ya que el tamaño de estas no se ajusta a la resolución, solo se ajusta la posición y proporciones de de los elementos a dibujar.
