### ISSUE TITLE
Enemigos

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#14]
Añadimos un enemigo al mapa.

- Tiene que contar con un sprite
- Debe detectar las colisiones.

**Comment by ecoronado96** [comment]
Hola compañeros @Pepooliet @MarinaFer @KinGJV @Javier-DlaP he estado pensando en como hacer que pueda ser mas animado el movimiento de los personajes y hacerlos con una leve IA, que os parecen las siguientes reglas:
1. El enemigo **elegirá de forma aleatoria moverse** en una dirección del eje X y del eje Y [arriba y abajo, y derecha e izquierda] o no moverse.
2. El enemigo **se moverá con el doble de posibilidades en la dirección en que se movió por ultima vez** para generar mayor apariencia de que los enemigos siguen una ruta de forma constante.
3. Cuando el enemigo este a una distancia X del jugador se seleccionara la dirección hasta el jugador como la del movimiento del enemigo, para simular toma de **aggro**.

Comentadme vuestra opinión.

**Comment by Javier-DlaP** [comment]
Yo había pensado en varios tipos de IA parecidas que se elijan aleatoriamente para el movimiento de los enemigos en plan como el tetris y que según el tipo de IA, tenga algo diferente en el sprite, como el color o alguna marca

**Comment by Pepooliet** [comment]
Me parece bastante correcto el comportamiento que has descrito.
Javier, con el tiempo del que disponemos es mejor dedicar el tiempo a otros objetivos.
Cuando dispongamos de una versión completa del juego podremos pensar en ello.

**Comment by ecoronado96** [comment]
### Implementado en enemigos
- [x] Sprite enemigo
- [x] Movimiento aleatorio
- [x] Colisiones
- [x] Aggro
