### ISSUE TITLE
Salto de estados

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#15]
Debemos añadir una casilla al mapa que nos permita. Al clickar esa casilla el personaje transiciona a otro estado (otro mapa)

**Comment by ecoronado96** [comment]
He incluido un par de casillas y un nuevo mapa, al pasar por encima de las casillas nos lleva al mapa nuevo.

**Comment by Pepooliet** [comment]
Perfecto! Con esto ya queda menos para tener una versión completa.
