### ISSUE TITLE
Enemigos (prueba)

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#17]
Hay que comprobar el comportamiento de los NPCs del mapa, agro y movimiento.

**Comment by ecoronado96** [comment]
Ya están los enemigos listos para las pruebas , recomiendo hacer distintas ejecuciones y saltos entre los dos escenarios implementados.

El commit de referencia para empezar con los test es el que tiene identificador c6ed3b9329ead056216b044a89e25e0edb84ceb6 .

Se ha detectado un pequeño error en uno de los enemigos que toma una velocidad de movimiento alto al inicio de la carga del juego en ciertas ocasiones, no tenemos claro a que se debe; espero que una vez introducido un menú en el juego sea solucionado.
