### ISSUE TITLE
Paquete de sonidos

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#19]
Hay que investigar en cuanto a los sonidos que podríamos utilizar en el juego, podemos empezar buscando un paquete o dos de sonidos. 
Tenemos que contar tanto con música ambiental como sonidos de personajes (enemigos y personaje principal)

**Comment by ecoronado96** [comment]
Para implementar los sonidos en el juego necesito que sean de cierto formato especifico para que los acepte slick. Según enuncia la documentación de slick:

> A single sound effect loaded from either OGG or XM/MOD file. Sounds are allocated to channels dynamically - if not channel is available the sound will not play.

Para los objetos Music es idéntico a los Sound. 
Os dejo el ejemplo de la inicialización de sonidos que aporta Slik2d para que veáis mas en detalla los formatos posibles:
```java
public void init(GameContainer container) throws SlickException {
		SoundStore.get().setMaxSources(32);
		
		myContainer = container;
		sound = new Sound("testdata/restart.ogg");
		charlie = new Sound("testdata/cbrown01.wav");
		try {
			engine = AudioLoader.getAudio("WAV", ResourceLoader.getResourceAsStream("testdata/engine.wav"));
		} catch (IOException e) {
			throw new SlickException("Failed to load engine", e);
		}
		music = musica = new Music("testdata/SMB-X.XM");
		//music = musica = new Music("testdata/theme.ogg", true);
		musicb = new Music("testdata/kirby.ogg", true);
		burp = new Sound("testdata/burp.aif");
		
		music.play();
	}
```

Avisadme en cuanto resolváis los sonidos.

**Comment by MarinaFer** [comment]
Acabo de subir los archivos de "Mazmorra" y "Ambiente bosque" en formato .ogg. El otro archivo no pega con el ambiente así que será mejor no usarlo.

**Comment by ecoronado96** [comment]
Ya, funciona, esta implementado.
