### ISSUE TITLE
Definir Objetos

### ISSUE THREAD

**Issue by ecoronado96** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#2]
# Objetos
Buenas a todos, genero esta issue para que vayamos creando un conjunto de objetos y sus variables los cuales vayamos a usar o necesitemos para el desarrollo del juego y así generar el conjunto de estos de una forma relacionada y correcta. Considero que es mejor que participemos todos en por lo menos mencionar cuales tenemos en mente para así no dejar olvidado ninguno.

### Estructura
La estructura de los objetos ha de ser identificada por paquetes, en principio he pensado en **personajes**, **objetos**, **mapas**; además de core y estados.
Haciendo de ejemplo en el caso de personajes este paquete ha de incluir una clase personaje con elementos básicos de este como su id vida inventario etc. , una clase personje_estatico y otra dinamico dependiendo de si se van a mover o por el mapa, una clase jugador(Ruby) , otra enemigo y otra comerciante.

### Participantes
Dicho esto me gustaría que @KinGJV me ayudase ha generar las estructura mas básica de los objetos ya que de momento hay poco con lo que hacer tareas de testing, yo me encargare de aquellas partes que tengan que ver con Slick. Por el momento no sera necesario que colabore en esta labor @Javier-DlaP, puede seguir trabajando las colisiones.

----

### Tareas
Esta es la lista de tareas, la iré actualizando según aparezcan ideas.
#### Paquete personajes
- [x] Personaje (id, vida, inventario)
- [x] Personaje_estatico (imagen)
- [x] Personaje_dinamico (sprite)
- [x] Jugador
- [x] Enemigo
- [x] Comerciante
- [x] Boss

#### Paquete elementos
- [x] Objeto <- Puede ser conveniente buscar otro nombre
- [x] Planta <- extiende de Objeto
- [x] Mapa
- [x] Hitbox

**Comment by Javier-DlaP** [comment]
He pensado que también se podría crear un objeto por cada tipo de planta, para así no tener que estar metiendo la dirección del sprite que referencia a esta planta cada vez que se crea una, sino con que creáramos por ejemplo una planta de fuego, la creación de esta sea totalmente automática.

**Comment by Pepooliet** [comment]
Me parece correcto. Se puede empezar con 3 plantas distintas, y luego se va expandiendo.
