### ISSUE TITLE
Sprites plantas

### ISSUE THREAD

**Issue by Javier-DlaP** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#20]
Para comenzar a trabajar con el funcionamiento del huerto sería necesario tener al menos dos sprites de la planta, uno tras plantar y otro al estar la planta ya crecida.
Te agradecería si lo pudieras hacer pronto para empezar con esto cuanto antes y que el tamaño que uses sea el que utilizarás en todas las demás plantas.

**Comment by ecoronado96** [comment]
Creo recordar que en los paquetes de mapa hay alguno de plantas que se podrían utilizar.

**Comment by MarinaFer** [comment]
Sí, de ese paquete he cogido la imagen. Igualmente he subido ya los sprites con solo la planta en cuestión.

**Comment by Javier-DlaP** [comment]
Ok, perfecto.
Creo una nueva issue para la interacción con el huerto y me pongo a ello.
