### ISSUE TITLE
Menú principal

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#22]
Abro issue para comenzar la creación del estado de menú principal, en que estarán presentes las opciones de **_Start_** y **_Exit_**, estando implementada la primera. La foto puede ser cualquiera.

**Comment by Javier-DlaP** [comment]
También podríamos poner una opción de cambiar la resolución de pantalla y si se quiere pantalla completa o no ya que no afectaría a las interfaces que se ajustan, solo sería cambiar un parámetro.

**Comment by Pepooliet** [comment]
Hemos tenido muchos problemas con la pantalla, además de que el profesor nos comentó que con tener una resolución que todos pudiesen poner (720p)
Por ahora nos centraremos en otras cosas.

**Comment by Javier-DlaP** [comment]
Te digo que los problemas que teníamos ya los he solucionado, la implementación que hice de los bocadillos permite que se cambie la resolución de pantalla y se ajuste automaticamente.

**Comment by ecoronado96** [comment]
El cambio de resolución afecta al tamaño de los elementos mostrados en pantalla, no siendo igual lo mostrado en unas pantallas que en otras. Si tu implementación para hacer que los bocadillos sean responsive funciona en cualquier situación y me la explicas bien; y siempre que tanto @Pepooliet y el resto del equipo este de acuerdo en el cambio y sus consecuencias por mi no hay problema.

**Comment by Pepooliet** [comment]
Teniendo las consecuencias que tiene, dejamos ese proyecto para cuando tengamos el juego hecho.
Cuando lo tengamos pensaremos en ello.

**Comment by ecoronado96** [comment]
El menú expuesto esta estructurado únicamente para 720p.
Se puede tener acceso a el desde las pantallas del juego pulsando la tecla  `ESC`.
El menú por el momento es capaz de introducirse en el estado juego, así como salir del juego, próximamente se incluirá las opciones de `nueva partida`, `cargar partida` y `guardar partida`, por el momento estos botones realizan acciones ficticias.
