### ISSUE TITLE
Arte de las mazmorras

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#23]
Abro issue para definir el arte de lo que serán las mazmorras del juego.
La idea sería crear un mapa básico que cuente con todo lo que se va a ver en un nivel de mazmorra cualquiera, haciendo uso de las distintas capas del tiled. Debe contar con lo siguiente.

- Muros
- Escaleras (cambiar de nivel)
- Spawns de enemigos

**Comment by MarinaFer** [comment]
He subido tanto un ejemplo del mapa, con las capas incorporadas, como el paquete de texturas básicas que se utilizarán.
