### ISSUE TITLE
Sprites para las plantas del huerto

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#25]
Necesitamos varios sprites para las plantas que formarán el huerto, 5-10 serán suficientes.
Así mismo, 2-3 sprites para semillas y otros 2-3 para los brotes.

**Comment by Javier-DlaP** [comment]
Con 3 tipos de planta de momento para las magias, y sus respectivos brotes y semillas valdría para empezar.

**Comment by MarinaFer** [comment]
![Plantas hechizos](https://user-images.githubusercontent.com/46962469/57219704-36e49280-6ff9-11e9-8618-b1b78da0ca37.png)
De momento podemos usar estas, para hechizo de fuego, rayo y agua.

**Comment by Javier-DlaP** [comment]
Dos cosas Marina:
La primera, no mandes todas las plantas en una matriz de imágenes, porque habías pasado una planta con dos sprites en la misma fila, si me pones ahora tres por cada planta me haces cambiar bastantes cosas, pero si ademas me lo subes así tengo que cambiar todo el funcionamiento de las plantas, por eso te pediría de subir las plantas en tres png diferentes.
La segunda, ¿por qué la planta amarilla son tan pequeñas? Parecen que son de la mitad de tamaño que la roja. Te diría que hacerlas más grandes.

**Comment by ecoronado96** [comment]
Necesitamos los sprites de las plantas ya para poder hacer los iconos y las animaciones del huerto, asi como de comercio y combate. Recuerdo que han de ser como la primera versión que se subio de estas 1*2 en cuanto a las imagenes y de tamaño 32x32 px.

Necesitamos también imágenes, NO sprites, para los iconos de las pociones de vida y daño.

**Comment by MarinaFer** [comment]
Listo.

**Comment by Javier-DlaP** [comment]
Las plantas dije que las necesitábamos en un formado de dos imágenes de las plantas por archivo, no todas en uno, adjunto un ejemplo (que es lo que pasaste en un principio).
Y además faltan los iconos de las semillas de cada tipo.
![Planta_fuego](https://user-images.githubusercontent.com/47185380/57786899-a31b7080-7734-11e9-9171-088f6460c6a8.png)

**Comment by MarinaFer** [comment]
Corregido, serían los archivos:
- Sprites Plantas (para las de fuego)
- Sprites Plantas Agua
- Sprites Plantas Rayo

Y sobre las semillas creo que sería mejor plantar los brotes y que de ahí saliesen ya las plantas, porque sino las semillas serían muy pequeñas y no se distinguirían unas de otras

**Comment by Javier-DlaP** [comment]
No, son semillas ya están implementadas así.

**Comment by MarinaFer** [comment]
Listo.

**Comment by Javier-DlaP** [comment]
**Necesito imágenes, no sprites**, al igual que los iconos de los objeto que pasaste.

**Comment by MarinaFer** [comment]
Corregido.

**Comment by Javier-DlaP** [comment]
Espero que los sprites del stardew valley no tengan copyright ya que sino el profesor puede poner pegas.

**Comment by MarinaFer** [comment]
De donde están sacados todos lo sprites, iconos y demás está explicado y nombrado a los autores en el documento de diseño.

**Comment by Javier-DlaP** [comment]
Sigo sin las plantas para el huerto en el formato indicado.

**Comment by Javier-DlaP** [comment]
Sigo sin las plantas para el huerto en el formato indicado.
