### ISSUE TITLE
Estado de combate

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#26]
Implementamos el estado de combate principal, **activado al colisionar** con un enemigo.
Lo que se verá por pantalla es muy parecido a un RPG: **dos sprites**, protagonista y enemigo, y **abajo un menú** de las opciones a tomar (lucha, objeto, huida)

**Comment by Javier-DlaP** [comment]
Pepe, Enrique está creando el sistema de guardado y yo estoy trabajando con el inventario, el huerto y los diálogos. No creo que podamos ponernos a ello hasta que acabemos cada uno lo nuestro.

**Comment by Pepooliet** [comment]
Claro, estoy poniendo la issue para trazar como debemos ir cumpliendo con los objetivos.
Hacedla cuando veáis que podéis.

**Comment by ecoronado96** [comment]
Voy a empezar con este estado mientras espero respuesta al email sobre el guardado, vamos a necesitar imágenes cuadradas como la que tenemos de Ruby y su abuela pero para los enemigos.

**Comment by Pepooliet** [comment]
Ok, abriendo issue

**Comment by ecoronado96** [comment]
## Combate
He acabado el combate. Queda pendiente de el testeo y correcciones y mejoras sobre lo realizado.

He aplicado las siguientes reglas

#### Ruby
- Acierto: 90% de probabilidad
- Critico: 10% de probabilidad
- Pociones: siempre efectivas
- Huida: 33% de probabilidad. En caso de fallo pierde el turno. En caso de acierto se vuelve al mapa y los enemigos se detienen momentáneamente.
- Daño: 10 puntos
#### Enemigo
- Acierto: 75% de probabilidad
- Critico: 10% de probabilidad
- Pociones: siempre efectivas
- Daño: 7 puntos
#### Boss
- Ataque: 90% de probabilidad
- Pociones: 10% de probabilidad
- Acierto: 90% de probabilidad sobre la probabilidad de ataque
- Critico: 10% de probabilidad sobre la probabilidad de ataque
- Daño: 10 puntos
#### Victoria
- Enemigo desaparece.
- Ruby gana el dinero de este y continua en el mismo mapa
#### Derrota
- Ruby vuelve a su casa
- Pierde 50 monedas
