### ISSUE TITLE
Sistema de guardado

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#27]
Issue dedicada para el sistema de guardado.

**Comment by ecoronado96** [comment]
Ya esta implementado el guardado y cargado de partida en el menú.

Se guardan los atributos de Ruby por el momento.

@Javier-DlaP ¿El huerto tiene algún set y get para coger los valores de este sin incluir clases de Slick? Algo así como lo que hiciste en el caso de las flores:

```java
int numFAgua = ruby.getInventario().getCantidad( new Flor_agua() );
```

**Comment by Javier-DlaP** [comment]
De momento no hay, pero cuando haga un commit de lo que llevo habrá una función que permite obtener una matriz de plantas

**Comment by ecoronado96** [comment]
La matriz de plantas no creo que me valga como tal, si esta compuesta por objetos planta entonces tienen su animación y por lo tanto elementos de slick, los cuales no me deja guardar al no ser serializables.

**Comment by Javier-DlaP** [comment]
Bug: Al cargar la partida tras guardarla teniendo previamente 0 objetos de un tipo, aparece x0 en el inventario, cuando en vez de poner x0 debería desaparecer ese objeto del inventario.

**Comment by ecoronado96** [comment]
Queda solucionado.

> Bug: Al cargar la partida tras guardarla teniendo previamente 0 objetos de un tipo, aparece x0 en el inventario, cuando en vez de poner x0 debería desaparecer ese objeto del inventario.
