### ISSUE TITLE
Sprites de combate

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#28]
Para el estado de combate necesitamos fotos cuadradas de los distintos enemigos, en el mismo formato que la del personaje principal.

**Comment by ecoronado96** [comment]
Concreta mente creo que me falta el de la planta. He usado de momento estos dos:

![RubyAvatar](https://user-images.githubusercontent.com/29814819/57183246-4d300880-6eaa-11e9-9305-9ed937d6f716.png)
![Boss](https://user-images.githubusercontent.com/29814819/57183248-4ef9cc00-6eaa-11e9-981b-3623876c2265.png)
 

Probablemente si queremos que el gato tenga dialogo vendría muy bien otra imagen para el.

**Comment by MarinaFer** [comment]
![Boceto planta](https://user-images.githubusercontent.com/46962469/57222424-cfcbdb80-7002-11e9-8a47-d999c77249fb.png) ![Boceto gato](https://user-images.githubusercontent.com/46962469/57222426-d0fd0880-7002-11e9-8942-4f40509e784a.png)
Acabo de añadir ambos bocetos, si necesitais algún otro reabrid esta issue y me pongo con ello.
