### ISSUE TITLE
Tenemos que definir posibles diálogos.

### ISSUE THREAD

**Issue by ecoronado96** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#29]
# Diálogos
Hay que ir pensando en diálogos para que digan los personajes del juego. Estos diálogos van a ir en relación a un array de la forma `{"Hola","mundo"}` siendo hola la cadena del primer personaje y mundo la del segundo.

Explicar la situación y personajes involucrados en la conversación y si veis que cualquiera de los diálogos se pueden mejorar comentarlo.

#### Ejemplo

Ruby habla con su abuela para comerciar.

|Personaje|Comentario|
|:---:|:---:|
|Ruby|¡Buenos días abuela!|
|Abuela|¡Hola Ruby! Te he traído un montón de semillas para tu huerto|
|Ruby|¡Genial!|

**Comment by Pepooliet** [comment]
Tenemos que definir los personajes con los que hablará.
Mientras tanto puedo ir intentando hacer un dialogo con la abuela.

**Comment by MarinaFer** [comment]
En principio hablará con la abuela, el boss final y si todos estáis de acuerdo con el gato, que este le puede contestar con un maullido o también hablando.

**Comment by Pepooliet** [comment]
### Ruby-Abuela: "¿Que haces?" Interacción Nº1
**Ruby**: "¿Que haces abuela?"
**Abuela**:"Descansar un poco hijita mia"
**Ruby**: "Oh bueno.."
**Abuela**: "Riega las plantas! **_[Posible tutorial aquí]_**"

**Comment by Pepooliet** [comment]
### Ruby-Abuela: "Semillas" Interacción Nº2
**Ruby**: "¿Oye abu, me darías semillas? Me he quedado sin"
**Abuela**: "¡Como no, si las vas lanzando por ahí!"
**Ruby**: "Prometo que esta vez no... todas"
**Abuela**: "Ay.. venga toma, pero haz el favor y planta alguna" **_[Posible tutorial aquí]_**

**Comment by Pepooliet** [comment]
### Ruby-Abuela: "Buenos días Nº1" [Dialogo inicio de día numero 1]
**Ruby**: "¡Buenos días abuela!"
**Abuela**: "¡Buenos días hijita mia! ¿Has dormido bien?"
**Ruby**: "*(Bostezo)*...Siii"
**Abuela**: "¿Me ayudas hoy con el jardín?"
**Ruby**: "Si me haces tortitas puede que si"
**Abuela**: "¿Pretendiendo que tu abuela compre tu amor? ¡Vergüenza debería darte! Vete a jugar, pero no te acerques al bosque"
**Ruby**: "Vale..." **_[Se dirije al bosque]_**

**NOTA**: Este podría ser el diálogo del primer día, una vez se dirige al bosque empieza lo del gato

**Comment by Pepooliet** [comment]
### Ruby-Abuela: "Buenos días Nº2" [Dialogo inicio de día genérico]
**Abuela**: "Buenos días Ruby"
**Ruby**: "Buenos días..."
**Abuela**: "..¿Que tal la busqueda de **_[Insertar nombre de gato aquí. Sugerencia: Cachirulo]_**, pudiste encontrarlo ayer?"
**Ruby**: Que va abuela, es un ninja
**Abuela**: "¡Ninja? ¿Que es eso?"
**Ruby**: ¡Un guerrero de las sombras! **_[Desaparece]_**
**Abuela**: "Ay que chiquilla..."

**Comment by Pepooliet** [comment]
Mañana me pongo con el del resto de personajes, las partes **_[Evidenciadas así]_** son notas para los programadores, sin embargo leedlo todos y decidme que opináis respecto a que sirvan de tutoriales etc

**Comment by ecoronado96** [comment]
> ### Ruby-Abuela: "Semillas" Interacción Nº2
> **Ruby**: "¿Oye abu, me darías semillas? Me he quedado sin"
> **Abuela**: "¡Como no, si las vas lanzando por ahí!"
> **Ruby**: "Prometo que esta vez no... todas"
> **Abuela**: "Ay.. venga toma, pero haz el favor y planta alguna" **_[Posible tutorial aquí]_**

Me gusta este dialogo bastante para el caso de que Ruby tenga todos sus elementos del inventario a 0 y no pueda comprar nada; incluso algo muy parecido, para el caso como dices de darle por primera vez semillas a Ruby estaría muy bien, e introducir a continuación un mini tutorial.

**Comment by Pepooliet** [comment]
### Ruby-Gato: "No te vayas" Interacción al entrar en el bosque
**_[Ruby entra en el bosque]_**
**Ruby**: "¿Eh _(Cachirulo)_, a donde vas?
**Gato**: "(Oh no, la chiquilla esta)"
**_[Aparece un enemigo]_**
**Gato**: "(Encima esto, yo me voy por patas..)" 
**_[Gato desaparece]_**
**Ruby**: "¡_(Cachirulo)_, no!"
**Ruby** (al enemigo): "Te vas a enterar!"
**_[Empieza el combate (¿Tutorial?)]_**
------**COMBATE**-------
**_[Acaba el combate]_**
**Ruby**: "Eso por ir asustando a los gatos de la gente"
**_[Empieza la mazmorra]_**

**NOTA**: El nombre _Cachirulo_ es el sugerido por el autor del guión, puede ser sustituido.

**Comment by Pepooliet** [comment]
### Ruby-Gato: "Te encontré" Interacción al final de la mazmorra
**_[Después de batalla con el boss final]_**
**Ruby**: "¡Por fin te encuentro, _(Cachirulo)_!"
**Gato**: "(Anda, tu por aqui)"
**Ruby**: "A saber que estabas haciendo en esta mazmorra"
**Gato**: "(Cosas de gatos, obviamente)"
**Ruby**:"Venga, vamos a casa con la abuela"
**Gato**: "(¡Buena idea, ya debe ser hora de la cena!)"
**_[Se van, acaba el juego]_**

**Comment by Pepooliet** [comment]
Las parentesis en el dialogo del gato implican que el gato no habla: es lo que piensa y dice, pero no lo que Ruby entiende.

**Comment by Pepooliet** [comment]
### Ruby-Boss Final "True final, 100% completed game" Conversación previa a la batalla con el jefe (opcional)
**Boss**: "¡Ah, finalmente un oponente! Soy el guardian de..."
**Ruby (le interrumpe)**: "¿Donde está _(Cachirulo)_?"
**Boss**: ¿_(Ca...Cachirulo)_? Que clase de conocimiento prohibido es ese, yo no he...
**Ruby (le interrumpe)**: "¡Donde...lo....TIENES!"
**Boss**: "(Pero de que va esta chiquilla) Oye, creo que te confundes...
**Ruby (le interrumpe)**: ¡AAAAHHHHH!
_**[Empieza el combate final]**_

**Comment by Pepooliet** [comment]
Esos serían todos los diálogos, cualquier cosa me decís y lo cambio.
Si no estáis de acuerdo con los eventos que les siguen lo podemos discutir.
