### ISSUE TITLE
Sistema de colisiones

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#3]
### Sistema de colisiones
En esta issue se van a anotar los progresos realizados en el sistema de colisiones.
Doy como válido un sistema que **evite** que el objeto personaje la atraviese, no es necesario un sistema avanzado por ahora.

**Comment by ecoronado96** [comment]
Buena solución <3.

**Comment by Javier-DlaP** [comment]
EZ
