### ISSUE TITLE
Fase granja a pocos fps

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#30]
Issue dedicada al testeo y resolución de la caída de fps en el mapa de la granja

**Comment by KinGJV** [comment]
He solucionado el problema usando como plantilla el .tmx de demo_map. Lo que he hecho ha sido recrear el .tmx de inicio con las dimensiones del de demo_map y funciona a unos 60 fps estables, también contiene las funcionalidades de inventario, diálogo y plantar/recoger que poseía el mapa original. Cuando podáis echadle un ojo y me comentáis si afecta en algo con el trabajo del equipo de programación.

**Comment by ecoronado96** [comment]
¿Podrías subirlo?, si crees que puede afectar al código genera una branch. Si solo son cambios en el mapa pero dicho mapa contiene las capas con los nombres mencionados no debería de dar ningún problema.

**Comment by KinGJV** [comment]
está subido en resources como casa_fps_altos no he tenido que tocar nada de la programación salvo la ruta para apuntar al tmx. Posee menos capas que el original pero en principio cumple todas las funciones que debería ya que las capas que faltan son visuales.
