### ISSUE TITLE
Reescalado del mapa

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#31]
Issue dedicada a ajustar el tamaño del mapa al tamaño de Ruby, tanto en la granja como en las mazmorras. También se pide adjuntar como se ha resuelto la issue.

**Comment by KinGJV** [comment]
he aumentado el tamaño de la granja doblando el tamaño del PNG donde se encuentran las texturas para así hacerlo a doble de tamaño. En este mapa existe una bajada de fps que, aunque, es notable, no hace que el mapa sea imposible de jugar

**Comment by Javier-DlaP** [comment]
Al hacer commit tienes que subir el archivo con el formato que fijó Enrique ya que sino el mapa no funciona en el juego, además al ejecutarlo no se está cargando el nuevo mapa ya que tiene otro nombre y aunque lo hagas cargar da error.

**Comment by KinGJV** [comment]
ya están subidos los archivos correctamente comprueba por favor si funcionan ahora

**Comment by Javier-DlaP** [comment]
Sigue sin ir, además tu puedes ver en tu ordenador como sigue ejecutando el mapa que teníamos antes.

**Comment by KinGJV** [comment]
Creada branch nueva llamada cambios_mapas para el testing de los próximos mapas sin necesidad de usar la master. Comprobad que se carga el mapa al doble de resolución que he creado sin errores. Gracias

**Comment by ecoronado96** [comment]
Acabo de probar, muy por encima; el rescalado en el branch se aplica correctamente pero no veo ninguna mejoría en los fps.

![image](https://user-images.githubusercontent.com/29814819/57641612-b522d500-75b5-11e9-85f9-5536ad812975.png)

Parece no afectar a las mecánicas, menos a una en concreto, el plantar, plantar esta definido como una acción en que la planta ocupa una casilla del mapa, no 4 como aparecen el huerto en la imagen. Si os fijáis hay señalada una flor de plantado en la imagen señalada. **Y aviso no vamos a cambiar la implementación de las funciones de plantado a estas alturas. Por lo tanto las flores van a ocupar lo mostrado en la imagen.**

En cuanto mejoren los fps me encargo de añadir los mapas a la rama master.

**Comment by Pepooliet** [comment]
Sigue yendo a 13 fps? No alcanza los 20?

**Comment by ecoronado96** [comment]
me iba a 20 en el ordenador de mesa y sigue yendo a 20, en el portátil espero un pelin menos entre 16-20 que es lo mismo que tenia antes.

**Comment by KinGJV** [comment]
hay 1 mapa que está escalado como antes pero con los fps sobre 38-40 si quereis modifico el código para que lo cargue el problema es que ruby se verá enorme a comparación con los mapas de mazmorras que si llevan el escalado

**Comment by Javier-DlaP** [comment]
Se podría probar si es cosa del pack de texturas cambiando alguna imagen de menor resolución por otra y si es así cambiamos las demás, y por otra parte habría que eliminar las imágenes de las flores del huerto.
