### ISSUE TITLE
Escenarios entre mazmorras

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#32]
Issue dedicada a hacer escenarios para las fases de **_tutorial de combate_** y **_final de juego_**
Serían dos salas rectangulares por las que se entra por un lado.
**Jesus** se encarga de la sala de la sala del **final del juego** (mazmorra de piedra)
**Marina** de la sala del **tutorial** (bosque)

**Comment by ecoronado96** [comment]
Vamos a ver, para aclararlo de la mejor forma posible. **Javi y yo acabamos de programar el jueves, como MUY tarde alargamos al viernes y muy a las malas.** Con esto **garantizamos** poder hacer **nuestra parte de la documentación** de forma correcta **para el sábado o domingo** como tarde y dejarlo acabado.

**No vamos a añadir nuevas pantallas de ultima hora**, tanto la pantalla de tutorial como la de boss final son estados no previstos en la previsión del juego, aclaramos, repetidas veces tutorial a través de los comentarios, como los de la abuela en el mapa principal; y de igual manera se aclaro que las mazmorras iban a ir comprendidas por un boss y unos enemigos todos ellas, sin pantallas especiales para boss especiales ni nada. Además de todo esto el juego no esta acabado, todavía tenemos trabajo que hacer para completarlo y eso va a ocupar el cupo de los dos próximos días en su totalidad. Por todo esto reitero no vamos a añadir mas pantallas de las ya pensadas.

Por lo tanto, **NO hagáis/penséis en hacer estos mapas y solucionar los problemas con el ÚNICO mapa que tenemos y que no funciona y acabar los mapas de mazmorra MÍNIMOS que necesitamos para el juego, nos quedan dos dias programando y tenemos UN mapa y ni si quiera funciona correctamente.**

Y por ultimo, y aclaro, **para acabar de programar el juego necesitamos las mazmorras previstas** y en principio estas tenían que haber estado el martes/miércoles de la semana pasada.

**Comment by KinGJV** [comment]
Mañana por la mañana estan las mazmorras subidas en la branch que creé de
testeo de mapas

**Comment by KinGJV** [comment]
he añadido los mapas de 3 mazmorras mas la del boss y un mapa de la granja con el escalado antiguo pero que funciona a 30+ fps estables. Tengo que investigar por qué ese mapa funciona con esos fps ya que está creado de la misma forma que el dimensionado a X2

**Comment by Pepooliet** [comment]
Ok, entendido.
No pude leerlo ayer.
Entonces se hará de acuerdo a lo que dices.
