### ISSUE TITLE
Paleta de colores de las interfaces

### ISSUE THREAD

**Issue by Javier-DlaP** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#33]
En la carpeta del proyecto de ruby se encuentran los diseños de las interfaces del combate y del menu de comercio.
Necesitamos los colores finales en formato rgb, en las interfaces de plantar, comercio, inventario y diálogos diría de usar colores marrones y verdes o verdes claros y oscuros. En el combate dan rienda suelta a vuestra imaginación.

**Comment by MarinaFer** [comment]
De momento los colores para el comercio, plantar, inventario y diálogos serían:
- RGB del fondo: 254 195 117
- RGB de los marcos: 210 113 18
- RGB de bordes y líneas: 140 57 0

Además de todos los textos en negro para que se vean bien.
![Interfaz](https://user-images.githubusercontent.com/46962469/57868381-2c00dd80-7803-11e9-94ee-dd111eaa5b71.JPG)

**Comment by ecoronado96** [comment]
Me parece un poco demasiado chillón, los naranjas tan brillantes me gustan para resaltar elementos, pero no como color principal de una interfaz.

**Comment by MarinaFer** [comment]
Os recuerdo que es un RPG dedicado a niñas de aprox. 15 años, por lo tanto pienso que tanto el diseño del juego como las interfaces deberían ser llamativas y el color que he elegido tampoco me parece chillón. No sé que opinan @KinGJV y @Pepooliet .

En todo caso si preferís cambiarlo y ya sabeis que colores utilizar esta issue estaría completa.

**Comment by ecoronado96** [comment]
Ya lo hemos implementado.
