### ISSUE TITLE
Bocetos

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#4]
### Bocetos de personajes
En esta issue se comentarán los progresos en los personajes.
Para ello hay que desarrollar una serie de bocetos:

- Boceto del personaje principal
- Bocetos de enemigos
---
**Personaje principal:**
Debe cumplir con los siguientes requisitos:
1.  Es una niña de edad comprendida entre los 10-15 años
2. Lleva una prenda u objeto de color rojo

El resto del diseño se deja a tu criterio
Además de un boceto estático, hay que hacer bocetos de la protagonista en movimiento, uno por cada dirección (Arriba, abajo, izquierda, derecha)
- [x] Personaje Principal completado 

**Enemigos y resto de personajes:**
Los NPCs son secundarios y como tales, sus diseños no necesitan ser tan elaborados.
- [x] Abuela de la protagonista
- [x] Enemigos (2 o 3), los diseños podrían estar inspirados en criaturas del campo

Estos se limitan a bocetos estáticos.

**Comment by MarinaFer** [comment]
Recordar a @Pepooliet que los diseños son de la base de datos de RPG Maker, seleccionados y editados posteriormente por mi, pero hay que citar en el documento de diseño los derechos de autor.

**Comment by Pepooliet** [comment]
Genial! Muchas gracias por recordármelo. Estoy rellenando un documento a parte con las fuentes.
