### ISSUE TITLE
Generación del mapa por clases

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#8]
Issue dedicada a la generación del mapa por clases.

**Comment by ecoronado96** [comment]
- **Carga de  mapa y hitbox, de elementos muro, enemigos, npcs y huerto.** - Completado
- **Renderización de elementos en pantalla.** - Completado
- **Actualización de posición de los elementos con hitbox respecto al movimiento.** - Completado
