### ISSUE TITLE
Sprite del personaje principal

### ISSUE THREAD

**Issue by Pepooliet** [TecnologiaVideojuegos/proyecto-videojuego-team-ruby#9]
Una vez desarrollado el boceto del personaje principal, hay que desarrollar el sprite correspondiente, en formato .PNG y con las siguientes posturas.

- [x] Estático
- [x] Movimiento (4 direcciones principales)
- [ ] Lanzando un hechizo (4 direcciones principales)

Los sprites deben estar de manera que el movimiento de personaje en pantalla sea coherente.

**Comment by ecoronado96** [comment]
En desarrollo hemos encontrado un ligero problema en el sprite de Ruby, en el movimiento cuya dirección es hacia abajo (1ª fila del sprite) hay uno de los frames (el central) que esta algún pixel por encima de los otros dos, produciendo un pequeño salto.

![image](https://user-images.githubusercontent.com/29814819/54825958-0d70e100-4caf-11e9-806f-681cd00db243.png)

Además encontramos un error parecido en el movimiento superior pero esta vez el desplazamiento de alguno de los frames es lateral y no puedo identificar cual es.

Los movimientos laterales del personaje están perfectos.

**Comment by Javier-DlaP** [comment]
Para dejar perfecto el sprite del personaje habría que:
-Bajar un pixel la vista de la primera fila, segunda columna
-Mover a la derecha un pixel de las vistas de la cuarta fila, primera columna y de la cuarta fila, segunda columna
-Mover a la derecha tres pixeles a la derecha la vista de la cuarta fila, tercera columna
-Aumentar el tamaño de las vistas de la primera fila, cuarta columna y de la tercera fila, cuarta columna un pixel hacia arriba y un pixel hacia abajo para tener un tamaño más parecido al del resto de las vista, para ello lo mas simple sería usar la altura de la vista de la cuarta fila, segunda columna

**Comment by MarinaFer** [comment]
Personaje actualizado y he comprobado que se han resuelto los problemas a la hora de moverse.
